# Generated by Django 3.1.3 on 2020-11-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoyItem',
            fields=[
                ('user', models.TextField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=30)),
                ('surname', models.TextField(blank=True, default='', max_length=60, null=True)),
                ('age', models.IntegerField()),
                ('address', models.TextField(max_length=60)),
                ('city', models.TextField(max_length=40)),
                ('province', models.TextField(max_length=40)),
                ('points', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CompanyItem',
            fields=[
                ('id_company', models.TextField(max_length=10, primary_key=True, serialize=False)),
                ('company', models.TextField(max_length=60)),
                ('address', models.TextField(max_length=60)),
                ('sector', models.TextField(max_length=20)),
            ],
        ),
    ]
