# Generated by Django 3.1.3 on 2020-11-25 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyItem',
            fields=[
                ('id_company', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=40)),
                ('province', models.CharField(max_length=40)),
                ('sector', models.CharField(choices=[('O', 'Ocio'), ('T', 'Tiendas'), ('R', 'Restaruración'), ('I', 'Internet')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionItem',
            fields=[
                ('id_question', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('desc_question', models.TextField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='UserItem',
            fields=[
                ('user', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('password', models.CharField(default='', max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(blank=True, default='', max_length=60, null=True)),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=40)),
                ('province', models.CharField(max_length=40)),
                ('points', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RetoItem',
            fields=[
                ('id_reto', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('desc_reto', models.CharField(max_length=100)),
                ('questions', models.ManyToManyField(to='docker_app.QuestionItem')),
            ],
        ),
        migrations.CreateModel(
            name='PromotionItem',
            fields=[
                ('id_promotion', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('D', 'Discount'), ('M', 'Merchandising'), ('T', 'Free tickets')], max_length=1)),
                ('desc_promotion', models.TextField(verbose_name=60)),
                ('id_company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='docker_app.companyitem')),
                ('reto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='docker_app.retoitem')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerItem',
            fields=[
                ('id_answer', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('desc_answer', models.CharField(max_length=50)),
                ('is_ok', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docker_app.questionitem')),
            ],
        ),
    ]
