# Generated by Django 3.1.3 on 2020-11-25 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docker_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boyitem',
            name='password',
            field=models.TextField(default='', max_length=10),
        ),
    ]
