# Generated by Django 3.1.3 on 2020-11-25 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docker_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotionitem',
            name='desc_promotion',
            field=models.TextField(max_length=60),
        ),
    ]
