# Generated by Django 3.1.3 on 2020-11-25 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docker_app', '0006_auto_20201125_2200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promotionitem',
            old_name='id_company',
            new_name='company',
        ),
    ]
