# Generated by Django 3.1.3 on 2020-11-26 06:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('docker_app', '0007_auto_20201125_2205'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_topic', models.TextField(max_length=100)),
                ('desc_topic', models.TextField(max_length=300)),
                ('url_topic', models.CharField(blank=True, max_length=200)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
