# Generated by Django 3.1.3 on 2020-11-26 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docker_app', '0008_topicitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicitem',
            name='title_topic',
            field=models.CharField(max_length=100),
        ),
    ]
